services:
  towerunite:
    build: .
    container_name: towerunite
    environment:
      - MAP_NAME=/Game/Maps/C_Condo
    ports:
      - "7777:7777/udp"
      - "27015:27015/udp"
    volumes:
      - ./TowerServer.ini:/data/Tower/Saved/Config/LinuxServer/TowerServer.ini
